2016-08-13 @ 14:53:48 CST ERROR [org.tfelab.common.db.Refacter:132] dropTables - java.lang.IllegalArgumentException: Field class java.lang.String for field FieldType:name=id,class=User is not valid for type com.j256.ormlite.field.types.IntType@d86a6f, maybe should be int
2016-08-13 @ 14:53:48 CST ERROR [org.tfelab.common.db.Refacter:132] dropTables - java.lang.IllegalArgumentException: Field class java.lang.String for field FieldType:name=id,class=Doctor is not valid for type com.j256.ormlite.field.types.IntType@d86a6f, maybe should be int
2016-08-13 @ 14:53:48 CST ERROR [org.tfelab.common.db.Refacter:132] dropTables - java.lang.IllegalArgumentException: Field class java.lang.String for field FieldType:name=id,class=Hospital is not valid for type com.j256.ormlite.field.types.IntType@d86a6f, maybe should be int
2016-08-13 @ 14:53:48 CST ERROR [org.tfelab.common.db.Refacter:132] dropTables - java.lang.IllegalArgumentException: Field class java.lang.String for field FieldType:name=id,class=DoctorService is not valid for type com.j256.ormlite.field.types.IntType@d86a6f, maybe should be int
2016-08-13 @ 14:53:48 CST ERROR [org.tfelab.common.db.Refacter:132] dropTables - java.lang.IllegalArgumentException: Field class java.lang.String for field FieldType:name=id,class=Section is not valid for type com.j256.ormlite.field.types.IntType@d86a6f, maybe should be int
2016-08-13 @ 14:53:48 CST ERROR [org.tfelab.common.db.Refacter:103] createTables - java.lang.IllegalArgumentException: Field class java.lang.String for field FieldType:name=id,class=User is not valid for type com.j256.ormlite.field.types.IntType@d86a6f, maybe should be int
2016-08-13 @ 14:53:48 CST ERROR [org.tfelab.common.db.Refacter:103] createTables - java.lang.IllegalArgumentException: Field class java.lang.String for field FieldType:name=id,class=Doctor is not valid for type com.j256.ormlite.field.types.IntType@d86a6f, maybe should be int
2016-08-13 @ 14:53:48 CST ERROR [org.tfelab.common.db.Refacter:103] createTables - java.lang.IllegalArgumentException: Field class java.lang.String for field FieldType:name=id,class=Hospital is not valid for type com.j256.ormlite.field.types.IntType@d86a6f, maybe should be int
2016-08-13 @ 14:53:48 CST ERROR [org.tfelab.common.db.Refacter:103] createTables - java.lang.IllegalArgumentException: Field class java.lang.String for field FieldType:name=id,class=DoctorService is not valid for type com.j256.ormlite.field.types.IntType@d86a6f, maybe should be int
2016-08-13 @ 14:53:48 CST ERROR [org.tfelab.common.db.Refacter:103] createTables - java.lang.IllegalArgumentException: Field class java.lang.String for field FieldType:name=id,class=Section is not valid for type com.j256.ormlite.field.types.IntType@d86a6f, maybe should be int
2016-08-13 @ 18:02:10 CST ERROR [org.tfelab.health.route.UserRoute:47] lambda$0 - Error create user. java.lang.NullPointerException
	at java.io.StringReader.<init>(Unknown Source) ~[?:1.8.0_71]
	at com.owlike.genson.Genson.deserialize(Genson.java:306) ~[genson-1.3.jar:?]
	at org.tfelab.common.json.JSON.fromJSON(JSON.java:50) ~[core-0.3.103.jar:?]
	at org.tfelab.health.route.UserRoute.lambda$0(UserRoute.java:30) ~[bin/:?]
	at spark.ResponseTransformerRouteImpl$1.handle(ResponseTransformerRouteImpl.java:47) [spark-core-2.3.jar:?]
	at spark.webserver.MatcherFilter.doFilter(MatcherFilter.java:162) [spark-core-2.3.jar:?]
	at spark.webserver.JettyHandler.doHandle(JettyHandler.java:61) [spark-core-2.3.jar:?]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189) [jetty-server-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52) [jetty-server-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134) [jetty-server-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.server.Server.handle(Server.java:524) [jetty-server-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:319) [jetty-server-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:253) [jetty-server-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273) [jetty-io-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95) [jetty-io-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93) [jetty-io-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303) [jetty-util-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148) [jetty-util-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136) [jetty-util-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671) [jetty-util-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589) [jetty-util-9.3.11.M0.jar:9.3.11.M0]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_71]

2016-08-13 @ 18:02:20 CST ERROR [org.tfelab.health.route.UserRoute:47] lambda$0 - Error create user. java.lang.NullPointerException
	at java.io.StringReader.<init>(Unknown Source) ~[?:1.8.0_71]
	at com.owlike.genson.Genson.deserialize(Genson.java:306) ~[genson-1.3.jar:?]
	at org.tfelab.common.json.JSON.fromJSON(JSON.java:50) ~[core-0.3.103.jar:?]
	at org.tfelab.health.route.UserRoute.lambda$0(UserRoute.java:30) ~[bin/:?]
	at spark.ResponseTransformerRouteImpl$1.handle(ResponseTransformerRouteImpl.java:47) [spark-core-2.3.jar:?]
	at spark.webserver.MatcherFilter.doFilter(MatcherFilter.java:162) [spark-core-2.3.jar:?]
	at spark.webserver.JettyHandler.doHandle(JettyHandler.java:61) [spark-core-2.3.jar:?]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189) [jetty-server-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52) [jetty-server-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134) [jetty-server-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.server.Server.handle(Server.java:524) [jetty-server-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:319) [jetty-server-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:253) [jetty-server-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273) [jetty-io-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95) [jetty-io-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93) [jetty-io-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303) [jetty-util-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148) [jetty-util-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136) [jetty-util-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671) [jetty-util-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589) [jetty-util-9.3.11.M0.jar:9.3.11.M0]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_71]

2016-08-13 @ 18:03:45 CST ERROR [org.tfelab.health.route.UserRoute:47] lambda$0 - Error create user. java.lang.NullPointerException
	at java.io.StringReader.<init>(Unknown Source) ~[?:1.8.0_71]
	at com.owlike.genson.Genson.deserialize(Genson.java:306) ~[genson-1.3.jar:?]
	at org.tfelab.common.json.JSON.fromJSON(JSON.java:50) ~[core-0.3.103.jar:?]
	at org.tfelab.health.route.UserRoute.lambda$0(UserRoute.java:30) ~[bin/:?]
	at spark.ResponseTransformerRouteImpl$1.handle(ResponseTransformerRouteImpl.java:47) [spark-core-2.3.jar:?]
	at spark.webserver.MatcherFilter.doFilter(MatcherFilter.java:162) [spark-core-2.3.jar:?]
	at spark.webserver.JettyHandler.doHandle(JettyHandler.java:61) [spark-core-2.3.jar:?]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189) [jetty-server-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52) [jetty-server-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134) [jetty-server-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.server.Server.handle(Server.java:524) [jetty-server-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:319) [jetty-server-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:253) [jetty-server-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273) [jetty-io-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95) [jetty-io-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93) [jetty-io-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303) [jetty-util-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148) [jetty-util-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136) [jetty-util-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671) [jetty-util-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589) [jetty-util-9.3.11.M0.jar:9.3.11.M0]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_71]

2016-08-13 @ 18:04:12 CST ERROR [org.tfelab.health.route.UserRoute:47] lambda$0 - Error create user. java.lang.NullPointerException
	at java.io.StringReader.<init>(Unknown Source) ~[?:1.8.0_71]
	at com.owlike.genson.Genson.deserialize(Genson.java:306) ~[genson-1.3.jar:?]
	at org.tfelab.common.json.JSON.fromJSON(JSON.java:50) ~[core-0.3.103.jar:?]
	at org.tfelab.health.route.UserRoute.lambda$0(UserRoute.java:30) ~[bin/:?]
	at spark.ResponseTransformerRouteImpl$1.handle(ResponseTransformerRouteImpl.java:47) [spark-core-2.3.jar:?]
	at spark.webserver.MatcherFilter.doFilter(MatcherFilter.java:162) [spark-core-2.3.jar:?]
	at spark.webserver.JettyHandler.doHandle(JettyHandler.java:61) [spark-core-2.3.jar:?]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189) [jetty-server-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52) [jetty-server-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134) [jetty-server-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.server.Server.handle(Server.java:524) [jetty-server-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:319) [jetty-server-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:253) [jetty-server-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273) [jetty-io-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95) [jetty-io-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93) [jetty-io-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303) [jetty-util-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148) [jetty-util-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136) [jetty-util-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671) [jetty-util-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589) [jetty-util-9.3.11.M0.jar:9.3.11.M0]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_71]

2016-08-13 @ 18:05:27 CST ERROR [org.tfelab.health.route.UserRoute:49] lambda$0 - Error create user. java.lang.NullPointerException
	at java.io.StringReader.<init>(Unknown Source) ~[?:1.8.0_71]
	at com.owlike.genson.Genson.deserialize(Genson.java:306) ~[genson-1.3.jar:?]
	at org.tfelab.common.json.JSON.fromJSON(JSON.java:50) ~[core-0.3.103.jar:?]
	at org.tfelab.health.route.UserRoute.lambda$0(UserRoute.java:32) ~[bin/:?]
	at spark.ResponseTransformerRouteImpl$1.handle(ResponseTransformerRouteImpl.java:47) [spark-core-2.3.jar:?]
	at spark.webserver.MatcherFilter.doFilter(MatcherFilter.java:162) [spark-core-2.3.jar:?]
	at spark.webserver.JettyHandler.doHandle(JettyHandler.java:61) [spark-core-2.3.jar:?]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189) [jetty-server-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52) [jetty-server-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134) [jetty-server-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.server.Server.handle(Server.java:524) [jetty-server-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:319) [jetty-server-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:253) [jetty-server-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273) [jetty-io-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95) [jetty-io-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93) [jetty-io-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303) [jetty-util-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148) [jetty-util-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136) [jetty-util-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671) [jetty-util-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589) [jetty-util-9.3.11.M0.jar:9.3.11.M0]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_71]

2016-08-13 @ 18:10:21 CST ERROR [org.tfelab.health.route.UserRoute:49] lambda$0 - Error create user. java.sql.SQLException: Unable to run insert stmt on object org.tfelab.health.model.User@354272ae: INSERT INTO `users` (`id` ,`name` ,`nick_name` ,`gender` ,`age` ,`password` ,`cell` ,`weixin` ,`insert_time` ,`update_time` ) VALUES (?,?,?,?,?,?,?,?,?,?)
	at com.j256.ormlite.misc.SqlExceptionUtil.create(SqlExceptionUtil.java:22) ~[ormlite-core-4.48.jar:?]
	at com.j256.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:135) ~[ormlite-core-4.48.jar:?]
	at com.j256.ormlite.stmt.StatementExecutor.create(StatementExecutor.java:450) ~[ormlite-core-4.48.jar:?]
	at com.j256.ormlite.dao.BaseDaoImpl.create(BaseDaoImpl.java:310) ~[ormlite-core-4.48.jar:?]
	at org.tfelab.health.model.User.insert(User.java:66) ~[bin/:?]
	at org.tfelab.health.route.UserRoute.lambda$0(UserRoute.java:42) ~[bin/:?]
	at spark.ResponseTransformerRouteImpl$1.handle(ResponseTransformerRouteImpl.java:47) [spark-core-2.3.jar:?]
	at spark.webserver.MatcherFilter.doFilter(MatcherFilter.java:162) [spark-core-2.3.jar:?]
	at spark.webserver.JettyHandler.doHandle(JettyHandler.java:61) [spark-core-2.3.jar:?]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189) [jetty-server-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52) [jetty-server-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134) [jetty-server-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.server.Server.handle(Server.java:524) [jetty-server-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:319) [jetty-server-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:253) [jetty-server-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273) [jetty-io-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95) [jetty-io-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93) [jetty-io-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303) [jetty-util-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148) [jetty-util-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136) [jetty-util-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671) [jetty-util-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589) [jetty-util-9.3.11.M0.jar:9.3.11.M0]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_71]
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '0' for key 'PRIMARY'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_71]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_71]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_71]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_71]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404) ~[mysql-connector-java-5.1.37.jar:5.1.37]
	at com.mysql.jdbc.Util.getInstance(Util.java:387) ~[mysql-connector-java-5.1.37.jar:5.1.37]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:934) ~[mysql-connector-java-5.1.37.jar:5.1.37]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3870) ~[mysql-connector-java-5.1.37.jar:5.1.37]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3806) ~[mysql-connector-java-5.1.37.jar:5.1.37]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2470) ~[mysql-connector-java-5.1.37.jar:5.1.37]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2617) ~[mysql-connector-java-5.1.37.jar:5.1.37]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2550) ~[mysql-connector-java-5.1.37.jar:5.1.37]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861) ~[mysql-connector-java-5.1.37.jar:5.1.37]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2073) ~[mysql-connector-java-5.1.37.jar:5.1.37]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2009) ~[mysql-connector-java-5.1.37.jar:5.1.37]
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5094) ~[mysql-connector-java-5.1.37.jar:5.1.37]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1994) ~[mysql-connector-java-5.1.37.jar:5.1.37]
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:410) ~[c3p0-0.9.5.1.jar:0.9.5.1]
	at com.j256.ormlite.jdbc.JdbcDatabaseConnection.insert(JdbcDatabaseConnection.java:170) ~[ormlite-jdbc-4.48.jar:?]
	at com.j256.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:91) ~[ormlite-core-4.48.jar:?]
	... 23 more

2016-08-13 @ 18:15:41 CST ERROR [org.tfelab.common.db.Refacter:138] dropTables - java.lang.IllegalArgumentException: Must specify one of id, generatedId, and generatedIdSequence with id
2016-08-13 @ 18:15:41 CST ERROR [org.tfelab.common.db.Refacter:138] dropTables - java.lang.IllegalArgumentException: Must specify one of id, generatedId, and generatedIdSequence with id
2016-08-13 @ 18:15:41 CST ERROR [org.tfelab.common.db.Refacter:138] dropTables - java.lang.IllegalArgumentException: Must specify one of id, generatedId, and generatedIdSequence with id
2016-08-13 @ 18:15:41 CST ERROR [org.tfelab.common.db.Refacter:138] dropTables - java.lang.IllegalArgumentException: Must specify one of id, generatedId, and generatedIdSequence with id
2016-08-13 @ 18:15:41 CST ERROR [org.tfelab.common.db.Refacter:138] dropTables - java.lang.IllegalArgumentException: Must specify one of id, generatedId, and generatedIdSequence with id
2016-08-13 @ 18:15:41 CST ERROR [org.tfelab.common.db.Refacter:109] createTables - java.lang.IllegalArgumentException: Must specify one of id, generatedId, and generatedIdSequence with id
2016-08-13 @ 18:15:41 CST ERROR [org.tfelab.common.db.Refacter:109] createTables - java.lang.IllegalArgumentException: Must specify one of id, generatedId, and generatedIdSequence with id
2016-08-13 @ 18:15:41 CST ERROR [org.tfelab.common.db.Refacter:109] createTables - java.lang.IllegalArgumentException: Must specify one of id, generatedId, and generatedIdSequence with id
2016-08-13 @ 18:15:41 CST ERROR [org.tfelab.common.db.Refacter:109] createTables - java.lang.IllegalArgumentException: Must specify one of id, generatedId, and generatedIdSequence with id
2016-08-13 @ 18:15:41 CST ERROR [org.tfelab.common.db.Refacter:109] createTables - java.lang.IllegalArgumentException: Must specify one of id, generatedId, and generatedIdSequence with id
2016-08-13 @ 18:29:57 CST ERROR [org.tfelab.health.route.UserRoute:47] lambda$0 - Error create user. java.sql.SQLException: Unable to run insert stmt on object org.tfelab.health.model.User@79e0cd67: INSERT INTO `users` (`name` ,`nick_name` ,`gender` ,`age` ,`password` ,`cell` ,`weixin` ,`insert_time` ,`update_time` ) VALUES (?,?,?,?,?,?,?,?,?)
	at com.j256.ormlite.misc.SqlExceptionUtil.create(SqlExceptionUtil.java:22) ~[ormlite-core-4.48.jar:?]
	at com.j256.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:135) ~[ormlite-core-4.48.jar:?]
	at com.j256.ormlite.stmt.StatementExecutor.create(StatementExecutor.java:450) ~[ormlite-core-4.48.jar:?]
	at com.j256.ormlite.dao.BaseDaoImpl.create(BaseDaoImpl.java:310) ~[ormlite-core-4.48.jar:?]
	at org.tfelab.health.model.User.insert(User.java:66) ~[bin/:?]
	at org.tfelab.health.route.UserRoute.lambda$0(UserRoute.java:40) ~[bin/:?]
	at spark.ResponseTransformerRouteImpl$1.handle(ResponseTransformerRouteImpl.java:47) [spark-core-2.3.jar:?]
	at spark.webserver.MatcherFilter.doFilter(MatcherFilter.java:162) [spark-core-2.3.jar:?]
	at spark.webserver.JettyHandler.doHandle(JettyHandler.java:61) [spark-core-2.3.jar:?]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189) [jetty-server-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52) [jetty-server-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134) [jetty-server-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.server.Server.handle(Server.java:524) [jetty-server-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:319) [jetty-server-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:253) [jetty-server-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273) [jetty-io-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95) [jetty-io-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93) [jetty-io-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303) [jetty-util-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148) [jetty-util-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136) [jetty-util-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671) [jetty-util-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589) [jetty-util-9.3.11.M0.jar:9.3.11.M0]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_71]
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry 'a' for key 'Index 2'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_71]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_71]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_71]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_71]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404) ~[mysql-connector-java-5.1.37.jar:5.1.37]
	at com.mysql.jdbc.Util.getInstance(Util.java:387) ~[mysql-connector-java-5.1.37.jar:5.1.37]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:934) ~[mysql-connector-java-5.1.37.jar:5.1.37]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3870) ~[mysql-connector-java-5.1.37.jar:5.1.37]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3806) ~[mysql-connector-java-5.1.37.jar:5.1.37]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2470) ~[mysql-connector-java-5.1.37.jar:5.1.37]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2617) ~[mysql-connector-java-5.1.37.jar:5.1.37]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2550) ~[mysql-connector-java-5.1.37.jar:5.1.37]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861) ~[mysql-connector-java-5.1.37.jar:5.1.37]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2073) ~[mysql-connector-java-5.1.37.jar:5.1.37]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2009) ~[mysql-connector-java-5.1.37.jar:5.1.37]
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5094) ~[mysql-connector-java-5.1.37.jar:5.1.37]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1994) ~[mysql-connector-java-5.1.37.jar:5.1.37]
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:410) ~[c3p0-0.9.5.1.jar:0.9.5.1]
	at com.j256.ormlite.jdbc.JdbcDatabaseConnection.insert(JdbcDatabaseConnection.java:170) ~[ormlite-jdbc-4.48.jar:?]
	at com.j256.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:91) ~[ormlite-core-4.48.jar:?]
	... 23 more

2016-08-13 @ 18:29:59 CST ERROR [org.tfelab.health.route.UserRoute:47] lambda$0 - Error create user. java.sql.SQLException: Unable to run insert stmt on object org.tfelab.health.model.User@670c272e: INSERT INTO `users` (`name` ,`nick_name` ,`gender` ,`age` ,`password` ,`cell` ,`weixin` ,`insert_time` ,`update_time` ) VALUES (?,?,?,?,?,?,?,?,?)
	at com.j256.ormlite.misc.SqlExceptionUtil.create(SqlExceptionUtil.java:22) ~[ormlite-core-4.48.jar:?]
	at com.j256.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:135) ~[ormlite-core-4.48.jar:?]
	at com.j256.ormlite.stmt.StatementExecutor.create(StatementExecutor.java:450) ~[ormlite-core-4.48.jar:?]
	at com.j256.ormlite.dao.BaseDaoImpl.create(BaseDaoImpl.java:310) ~[ormlite-core-4.48.jar:?]
	at org.tfelab.health.model.User.insert(User.java:66) ~[bin/:?]
	at org.tfelab.health.route.UserRoute.lambda$0(UserRoute.java:40) ~[bin/:?]
	at spark.ResponseTransformerRouteImpl$1.handle(ResponseTransformerRouteImpl.java:47) [spark-core-2.3.jar:?]
	at spark.webserver.MatcherFilter.doFilter(MatcherFilter.java:162) [spark-core-2.3.jar:?]
	at spark.webserver.JettyHandler.doHandle(JettyHandler.java:61) [spark-core-2.3.jar:?]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189) [jetty-server-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52) [jetty-server-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134) [jetty-server-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.server.Server.handle(Server.java:524) [jetty-server-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:319) [jetty-server-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:253) [jetty-server-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273) [jetty-io-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95) [jetty-io-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93) [jetty-io-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303) [jetty-util-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148) [jetty-util-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136) [jetty-util-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671) [jetty-util-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589) [jetty-util-9.3.11.M0.jar:9.3.11.M0]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_71]
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry 'a' for key 'Index 2'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_71]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_71]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_71]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_71]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404) ~[mysql-connector-java-5.1.37.jar:5.1.37]
	at com.mysql.jdbc.Util.getInstance(Util.java:387) ~[mysql-connector-java-5.1.37.jar:5.1.37]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:934) ~[mysql-connector-java-5.1.37.jar:5.1.37]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3870) ~[mysql-connector-java-5.1.37.jar:5.1.37]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3806) ~[mysql-connector-java-5.1.37.jar:5.1.37]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2470) ~[mysql-connector-java-5.1.37.jar:5.1.37]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2617) ~[mysql-connector-java-5.1.37.jar:5.1.37]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2550) ~[mysql-connector-java-5.1.37.jar:5.1.37]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861) ~[mysql-connector-java-5.1.37.jar:5.1.37]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2073) ~[mysql-connector-java-5.1.37.jar:5.1.37]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2009) ~[mysql-connector-java-5.1.37.jar:5.1.37]
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5094) ~[mysql-connector-java-5.1.37.jar:5.1.37]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1994) ~[mysql-connector-java-5.1.37.jar:5.1.37]
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:410) ~[c3p0-0.9.5.1.jar:0.9.5.1]
	at com.j256.ormlite.jdbc.JdbcDatabaseConnection.insert(JdbcDatabaseConnection.java:170) ~[ormlite-jdbc-4.48.jar:?]
	at com.j256.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:91) ~[ormlite-core-4.48.jar:?]
	... 23 more

2016-08-13 @ 18:30:05 CST ERROR [org.tfelab.health.route.UserRoute:47] lambda$0 - Error create user. java.sql.SQLException: Unable to run insert stmt on object org.tfelab.health.model.User@2ab3dece: INSERT INTO `users` (`name` ,`nick_name` ,`gender` ,`age` ,`password` ,`cell` ,`weixin` ,`insert_time` ,`update_time` ) VALUES (?,?,?,?,?,?,?,?,?)
	at com.j256.ormlite.misc.SqlExceptionUtil.create(SqlExceptionUtil.java:22) ~[ormlite-core-4.48.jar:?]
	at com.j256.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:135) ~[ormlite-core-4.48.jar:?]
	at com.j256.ormlite.stmt.StatementExecutor.create(StatementExecutor.java:450) ~[ormlite-core-4.48.jar:?]
	at com.j256.ormlite.dao.BaseDaoImpl.create(BaseDaoImpl.java:310) ~[ormlite-core-4.48.jar:?]
	at org.tfelab.health.model.User.insert(User.java:66) ~[bin/:?]
	at org.tfelab.health.route.UserRoute.lambda$0(UserRoute.java:40) ~[bin/:?]
	at spark.ResponseTransformerRouteImpl$1.handle(ResponseTransformerRouteImpl.java:47) [spark-core-2.3.jar:?]
	at spark.webserver.MatcherFilter.doFilter(MatcherFilter.java:162) [spark-core-2.3.jar:?]
	at spark.webserver.JettyHandler.doHandle(JettyHandler.java:61) [spark-core-2.3.jar:?]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189) [jetty-server-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52) [jetty-server-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134) [jetty-server-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.server.Server.handle(Server.java:524) [jetty-server-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:319) [jetty-server-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:253) [jetty-server-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273) [jetty-io-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95) [jetty-io-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93) [jetty-io-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303) [jetty-util-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148) [jetty-util-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136) [jetty-util-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671) [jetty-util-9.3.11.M0.jar:9.3.11.M0]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589) [jetty-util-9.3.11.M0.jar:9.3.11.M0]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_71]
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry 'b' for key 'Index 2'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_71]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_71]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_71]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_71]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404) ~[mysql-connector-java-5.1.37.jar:5.1.37]
	at com.mysql.jdbc.Util.getInstance(Util.java:387) ~[mysql-connector-java-5.1.37.jar:5.1.37]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:934) ~[mysql-connector-java-5.1.37.jar:5.1.37]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3870) ~[mysql-connector-java-5.1.37.jar:5.1.37]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3806) ~[mysql-connector-java-5.1.37.jar:5.1.37]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2470) ~[mysql-connector-java-5.1.37.jar:5.1.37]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2617) ~[mysql-connector-java-5.1.37.jar:5.1.37]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2550) ~[mysql-connector-java-5.1.37.jar:5.1.37]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861) ~[mysql-connector-java-5.1.37.jar:5.1.37]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2073) ~[mysql-connector-java-5.1.37.jar:5.1.37]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2009) ~[mysql-connector-java-5.1.37.jar:5.1.37]
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5094) ~[mysql-connector-java-5.1.37.jar:5.1.37]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1994) ~[mysql-connector-java-5.1.37.jar:5.1.37]
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:410) ~[c3p0-0.9.5.1.jar:0.9.5.1]
	at com.j256.ormlite.jdbc.JdbcDatabaseConnection.insert(JdbcDatabaseConnection.java:170) ~[ormlite-jdbc-4.48.jar:?]
	at com.j256.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:91) ~[ormlite-core-4.48.jar:?]
	... 23 more

